kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "hello-sinatra-pipeline"
spec:
  source:
    type: "Git"
    git:
      uri: "https://github.com/nekop/hello-sinatra"
  strategy:
    type: "JenkinsPipeline"
    jenkinsPipelineStrategy:
      jenkinsfilePath: "pipeline/Jenkinsfile"

